# #!/bin/bash
# export CUDA_VISIBLE_DEVICES=4,5,6,7
deepspeed --include=localhost:0,1,2,3,4,5,6,7 --master_port=29501 path/deepspeed_train.py \
    --deepspeed path/scripts/zero2.json \
    --useLorafinetune False \
    --model_name_or_path /path/Vicuna-7b-v1.5 \
    --version plain \
    --data_path  path/blip_laion_cc_sbu_558k.json \
    --image_folder path/images \
    --vision_tower path/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir path/EventChat-v1.5-7b-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 64 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 400 \
    --save_total_limit 4 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
