#!/bin/bash
#export CUDA_VISIBLE_DEVICES=4,5,6,7
deepspeed --include=localhost:0,1,2,3,4,5,6,7 --master_port=29506 path/deepspeed_train.py \
    --deepspeed path/scripts/zero3.json \
    --useLora False \
    --pretrain_mm_mlp_adapter path/mm_projector.bin \
    --model_name_or_path path/model/vicuna-7b-v1.5 \
    --version v1 \
    --stage3 True \
    --use_feature_adaptor True \
    --pretrain_feature_adaptor path/feature_adaptor.bin \
    --spatial_temporal_encoder True \
    --data_path  path/gestures_instruct_train.json \
    --image_folder path/images \
    --event_folder path/task_tuning/event \
    --vision_tower path/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir path/EventChat-v1.5-7b-task-lora \
    --output_mm_mlp_adapter path/EventChat-v1.5-7b-task-lora\
    --num_train_epochs 8 \
    --per_device_train_batch_size 64 \
    --per_device_eval_batch_size 0 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 200 \
    --save_total_limit 4 \
    --learning_rate 1e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb